name: Check

on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
        with:
          fail-mode: true
      - name: "Install Nix ❄️"
        uses: DeterminateSystems/nix-installer-action@v3
      - run: nix run --extra-experimental-features 'nix-command flakes'  nixpkgs#statix -- check